### ISSUE TITLE
Docs examples

### ISSUE THREAD

**Issue by jackfirth** [jsmaniac/subtemplate#4]
This library is really interesting! Unfortunately, the documentation is very dense and I find it difficult to get a handle on. A few REPL examples and maybe a Guide-like section to the docs would go a long way to improving my ability to use this library.

**Comment by SuzanneSoy** [comment]
@jackfirth Thanks for taking a look at `subtemplate`! The docs were indeed thoroughly lacking examples. I added examples for all the main features. I admit I had a lack of inspiration for some, so parts look a bit more like unit tests than proper documentation examples :-( .

Please do comment here or open new issues if you feel some parts are still unclear, or if the use case for some features is elusive.

Thanks!
